### ISSUE TITLE
Stamina bar glitch

### ISSUE THREAD

**Issue by EchoTTV** [SilentNightSound/GI-Model-Importer#124]
I dont know what I did or what I pressed but now in Genshin the stamina bar is as long as a botw stamina bar that doesnt move and i have tried pressing a lot of keys but nothing will work.. what do i do? I want my normal stamina bar. its a 3dmigoto thing because it doesnt happen when i run the game without it
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/107978459/409c8ede-e2f4-46d2-9655-f04e798b9fd8)

**Comment by AikoTM** [comment]
I got the same issue. :c

**Comment by leotorrez** [comment]
The issue is caused by an outdated mod or shader. You can solve it with a fresh install or by pinpointing the clueprit.

The fastest way to find it is to turn off shaderfixes and see if the issue is solved. Otherwise the issue is in Mods.

turn off half of your mods by moving them into another folder, if the issue persists then do the same with the remaining files till you find the exact one that is causing the wrong mod.
