### ISSUE TITLE
about GIMI please

### ISSUE THREAD

**Issue by skorpionred100** [SilentNightSound/GI-Model-Importer#129]
Sorry for asking about how the GIMI application works, but I was talking to a genshin impact technical service, and I wanted to know if GIMI modifies the game's own files in any way or how it works, to know if it can be legal or if we can get in trouble for using it

**Comment by leotorrez** [comment]
There is a certain risk of getting banned because it is an external program being used onto their assets. HOWEVER it does not modify game files, instead it grabs the temporary information saved in the video card and modifies it before it reaches your screen. Hence rendering something different. There is no safe modding method. But this is as safe as it gets.

**Comment by skorpionred100** [comment]
> Existe un cierto riesgo de ser prohibido porque se utiliza un programa externo en sus activos. SIN EMBARGO, no modifica los archivos del juego, sino que toma la información temporal guardada en la tarjeta de video y la modifica antes de que llegue a la pantalla. Por lo tanto, representa algo diferente. No existe un método de modificación seguro. Pero esto es lo más seguro posible.

What happens is that I talk to the technical service and they tell me that as long as I don't modify the game files it may be legal

**Comment by leotorrez** [comment]
Well in that case you should be safe. Can you dm me a screenshot of that support ticket? im curious of their wording

**Comment by SilentNightSound** [comment]
Has had no response in over 30 days, issue appears to be resolved. Closing ticket
