### ISSUE TITLE
Unable to load 3DMigoto "d3d11.dll"

### ISSUE THREAD

**Issue by Vitra2050** [SilentNightSound/GI-Model-Importer#148]
When I try to run 3Dmigoto for Genshin Impact I get this error "unable to load d3d11.dll", I already tried to put the game path in d3dx.ini but nothing works, so I don't know what to do.
![image](https://github.com/SilentNightSound/GI-Model-Importer/assets/148423348/61acb8eb-a593-47ed-bc98-7dbea8be777d)

**Comment by SilentNightSound** [comment]
Hello. Most of the time this is due to not extracting the zip file before running the exe. Also, try restarting PC and make sure the 3dmigoto exe is not in a protected folder and that the DLL hasn't been eaten by anti-virus.

For more setup help, please visit https://discord.com/invite/agmg which has a dedicated channel for setup questions

**Comment by Vitra2050** [comment]
I just asked on that discord server and they couldn't tell me how to fix my problem, I will try what you propose.
