### ISSUE TITLE
broken mods?

### ISSUE THREAD

**Issue by Xaniiax** [SilentNightSound/GI-Model-Importer#297]
This morning when i wanted to play with mods, all of my mods broke? now I tried reinstalling the mod importer, and reinstalling the fix for the mods, but nothing is working. I haven't tried reinstalling all the mods yet because that would be a hassle but if this is an issue for anyone else or if I need to reinstall all the mods I have, please let me know !

**Comment by JACOBnotpro** [comment]
some people said that it was because of `Dynamic Character Resolution`. Try to turn this off and f10 to reload all the mod 
I already try this and it not work for me. Take an effort to do it and let me know if it works?
![Screenshot (653)](https://github.com/user-attachments/assets/5c436708-8248-431e-9cf0-d3dd4a914a86)
![Screenshot (651)](https://github.com/user-attachments/assets/aac23396-74ec-4ed1-9792-918778f160ee)

**Comment by leotorrez** [comment]
this issue functionality is for bugs related to the tool. Not mod issues in particular, for those feel free to ask for help in discord.gg/agmg
