### ISSUE TITLE
skins not loading

### ISSUE THREAD

**Issue by keiplid** [SilentNightSound/GI-Model-Importer#38]
i did everything it says but it cant load skin, changed the location and there  is green text on the screen
![unknown](https://user-images.githubusercontent.com/116032377/196267976-8b65a996-099c-4500-bc52-74d68efa10fe.png)

**Comment by SilentNightSound** [comment]
If the green text shows up but the mod isn't loading, that is an issue with the mod itself.

Is the mod unzipped? Is it in the the Mods folder (of the program you are running if you have multiple ones)? Do other mods work? You can use those questions to narrow down if it is a specific mod or all mods

**Comment by ok-wei** [comment]
I have same problem，and the green text didn't show at all, the skin didn't load yet

**Comment by SilentNightSound** [comment]
If the green text isn't showing up, it is almost always one of two things:

1) You are using the for playing version. The green text only shows up when using dev (both versions should load mods though)
2) The target = line in the .ini is set incorrectly. Double check it is pointing to the right location, and that it uses single \ instead of double \\. You can also try using `target = GenshinImpact.exe` instead of a path, and it will try and load it by process name instead of location

**Comment by LJY7812** [comment]
I have same problem, green text did show at all

**Comment by sllvee** [comment]
restart your computer，because game.exe don't fully colse,you will normal run by kill exisited game.exe
重启电脑，因为你的原神进程没有完全关闭，你可以杀死这个进程来正常运行3dmigoto，一般是你加载过一次然后关闭游戏重新加载才有，Alt+F4真好用

**Comment by shinobusuki** [comment]
I have the same problem.3dmigoto loader console window suddenly closes, and the skins doesn't load at all. I'm sure I've followed the correct stpes/

**Comment by SilentNightSound** [comment]
Does the issue still persist? If not, I will close the ticket.

**Comment by Xalvador3133** [comment]
i also have the same problem it said Checking if 3DMigoto successfully loaded:5 any fixes yet?

**Comment by SilentNightSound** [comment]
Closing this ticket - for troubleshooting getting the program to run, please use the verification-support channel in the AGMG discord
