### ISSUE TITLE
Can't work with Ver.3.2(China mihoyo ver.)

### ISSUE THREAD

**Issue by Chadaid** [SilentNightSound/GI-Model-Importer#59]
I am sure that I have completed all the operations in readme, and I really use the development version. But in fact, green text did not appear. The model in the game has not changed, even after I press the F10 key. During the GIMI startup process, I did not see any abnormal prompts. This makes me very confused. Is it that GIMI can't work properly in the computer of AMD platform?

**Comment by Chadaid** [comment]
![image](https://user-images.githubusercontent.com/123052030/213366539-24670ade-6787-4c77-bf3b-c9a4b7d2d7b9.png)
That's what I see during yuanshen.exe starting up

**Comment by Chadaid** [comment]
I have used Akebi, and Akebi can run normally on my computer. I have tried to use GIMI when Akebi is enabled or not, but GIMI does not work properly in both cases.

**Comment by SilentNightSound** [comment]
GIMI should work on all versions of genshin by default - the most common issue by far is the path not being set correctly. Double check the path is set, and also try setting the target to `target = YuanShen.exe` which attempts to load it by process name instead of path.

The other thing to check is if you are running as admin, which can also sometimes be an issue.

**Comment by qiyimoli** [comment]
Try to perform an uninstall.bat

**Comment by SilentNightSound** [comment]
No update in several weeks, and program seems to work on 3.2 from my testing. Closing ticket
