### ISSUE TITLE
cant download

### ISSUE THREAD

**Issue by pastel-n0va** [SilentNightSound/GI-Model-Importer#63]
the link to download it wont work, it seems to be blocked on my device..

**Comment by SilentNightSound** [comment]
It shouldn't be? I don't think github is blocked anywhere that I know of. Make sure to download from releases (https://github.com/SilentNightSound/GI-Model-Importer/releases) and double check your browser isn't deleting the files for some reason. Otherwise, that is an issue with your system not the program

**Comment by SilentNightSound** [comment]
No update or comment in several weeks, closing ticket as resolved.
